# Generated by Django 5.2.5 on 2025-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Agriculture, natural resources and rural development', 'Agriculture, natural resources and rural development'), ('Education', 'Education'), ('Energy', 'Energy'), ('Finance', 'Finance'), ('Health', 'Health'), ('Industry and trade', 'Industry and trade'), ('Information and communication technology', 'Information and communication technology'), ('Multisector', 'Multisector'), ('Public sector management', 'Public sector management'), ('Transport', 'Transport'), ('Water and other urban infrastructure and services', 'Water and other urban infrastructure and services'), ('Uncategorized', 'Uncategorized')], help_text='Name of the sector', max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='updated',
        ),
        migrations.AddField(
            model_name='partner',
            name='consultant_source',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='current_partnership_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='hq',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='sector',
            field=models.ManyToManyField(blank=True, help_text='Select one or more sectors for this firm', to='partners.sector'),
        ),
    ]
