# Generated by Django 5.2.5 on 2025-10-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
