# Generated by Django 5.2.5 on 2025-09-02 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_sector_alter_partner_options_remove_partner_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='sector',
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['firm_name']},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='consultant_source',
        ),
        migrations.AddField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='current_partnership_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='hq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
